//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DutyFloorWatch
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public System.TimeSpan TimeFinish { get; set; }
        public string Type { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
