//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudSovietPosition
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public string Description { get; set; }
    
        public virtual StudSovietMember StudSovietMember { get; set; }
    }
}
